IF
        Global("h_SpawnBM1","GLOBAL",0)
THEN
        RESPONSE #100
                 CreateCreature("h_bmarkc",[93.285],E)
                 CreateCreature("h_bmar2c",[437.262],W)
                 CreateCreature("h_bmar4c",[191.173],S)
                 CreateCreature("h_bmar5c",[325.177],S)
                 CreateCreature("h_thalic",[227.306],S)
                 SetGlobal("h_SpawnBM1","GLOBAL",1)
                 Continue()
END