IF
         See([PC])
	 Global("h_SpawnRichard","GLOBAL",1)
THEN
	 RESPONSE #100
	          PlaySound("h_shamus")
		  SmallWait(1)
		  StartDialog("h_richad",[PC])
		  SetGlobal("h_SpawnRichard","GLOBAL",2)
END

IF
         See([PC])
         Global("h_SpawnRichard","GLOBAL",3)
THEN
	 RESPONSE #100
		  SmallWait(1)
		  StartDialog("h_richad",[PC])
END

IF
         See([PC])
         Dead("h_snak2c")
THEN
	 RESPONSE #100
		  SmallWait(3)
		  StartDialog("h_richad",[PC])
END


