IF
        Global("h_SpawnAmrius","GLOBAL",0)

THEN
        RESPONSE #100
                 CreateCreature("h_amriuc",[377.350],E)
                 SetGlobal("h_SpawnAmrius","GLOBAL",1)
                 Continue()
END

IF
        TimeOfDay(NIGHT)
        Global("h_SpawnTheresa","GLOBAL",1)

THEN
        RESPONSE #100
                 CreateCreature("h_therec",[235.129],N)
                 SetGlobal("h_SpawnTheresa","GLOBAL",2)
                 Continue()
END